---
- hosts: "{{ inventory_vm_name }}"
  become: true
  vars:
    force_register: false
    install_pkgs_list:
      - vim
      - insights-client
      - git
    register_insights: true
    epel: false
    # https://access.redhat.com/articles/simple-content-access
    # XXX someone figure out how to simplify subs process by using sca
    # Currently it's both slow and risky.
    sca: true
  tasks:

    - name: Subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ rh_subs_username }}"
        password: "{{ rh_subs_password }}"
        force_register: "{{ force_register }}"
      tags: subs

    - name: Install Epel repos
      ansible.builtin.dnf:
        # yamllint disable-line rule:line-length
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      when: epel | bool
      tags: regs

    - name: install stuff
      ansible.builtin.dnf:
        name: "{{ install_pkgs_list }}"
        state: present
      tags: packages

    - name: Register the insights client
      redhat.insights_register:
        state: present

